language: node_js
services:
  - memcached
node_js:
  - "4.0.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_script: npm install
script: NODE_ENV=production mocha -R spec test/spec/server --recursive
after_script: grunt deploy