language: node_js
env:
  - CXX=g++-4.8
services:
  - memcached
node_js:
  - "4.0.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
addons:
  apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - g++-4.8
sudo: false
before_script: 
  - npm install
script:
  - NODE_ENV=production mocha -R spec test/spec/server --recursive
after_script: 
  - grunt deploy