language: node_js
env:
  - CXX=g++-4.8
services:
  - memcached
node_js:
  - "14.15.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: false
after_script: 
  - npm run deploy