language: node_js
compiler:
  - gcc
services:
  - memcached
node_js:
  - "4.0.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
before_script: 
  - npm install
script:
  - NODE_ENV=production mocha -R spec test/spec/server --recursive
after_script: 
  - grunt deploy